const timesArrayKey = "3x3ohcmllTimes";
const selectionArrayKey = "3x3ohcmllselection";
var trainerTitle = "OH CMLL Trainer";
var preRotations = [''];
var postRotations = [''];
var preMoves = ["", "U", "U'", "U2"];
var postMoves = preMoves;
var selCases = [];
var maxAlgsPerRow = 6;