const timesArrayKey = "3x3fsoTimesArray";
const selectionArrayKey = "3x3fsoSelection";
var trainerTitle = "3x3 FSO Trainer";
var preRotations = [""];
var postRotations = [""];
var preMoves = ["U", "U'", "U2"];
var postMoves = preMoves;
var selCases = [];
var maxAlgsPerRow = 8;