const timesArrayKey = "3x3bldufTimes";
const selectionArrayKey = "3x3bldufSelection";
var trainerTitle = "3x3 BLD UFR Trainer";
var preRotations = [''];
var postRotations = [''];
var preMoves = [""];
var postMoves = preMoves;
var selCases = [];
var maxAlgsPerRow = 6;