const timesArrayKey = "3x3zbllTimes";
const selectionArrayKey = "3x3zbllselection";
var trainerTitle = "3x3 ZBLL Trainer";
var preRotations = [''];
var postRotations = [''];
var preMoves = ["", "U", "U'", "U2"];
var postMoves = preMoves;
var selCases = [];
var maxAlgsPerRow = 6;