const timesArrayKey = "octaminxTCPTimesArray";
const selectionArrayKey = "octaminxTCPSelection";
var trainerTitle = "Octaminx TCP Trainer"
var maxAlgsPerRow = 6;
var preRotations = [''];
var postRotations = [''];
var preMoves = ["", "U", "U'"];
var postMoves = preMoves;
var selCases = [];