const timesArrayKey = "3x3zblsTimes";
const selectionArrayKey = "3x3zblsselection";
var trainerTitle = "3x3 ZBLS Trainer";
var preRotations = ["", "y", "y'", "y2"];
var postRotations = ["", "y", "y'", "y2"];
var preMoves = ["", "U", "U'", "U2"];
var postMoves = preMoves;
var selCases = [];
var maxAlgsPerRow = 6;