const timesArrayKey = "ftolbtTimesArray";
const selectionArrayKey = "ftolbtSelection";
var trainerTitle = "FTO LBT Trainer";
var preRotations = [""];
var postRotations = [""];
var preMoves = ["U", "U'"];
var postMoves = preMoves;
var selCases = [];
var maxAlgsPerRow = 4;