const timesArrayKey = "ftolbtTimesArray.1";
const selectionArrayKey = "ftolbtSelection.1";
var trainerTitle = "FTO LBT Trainer";
var preRotations = [""];
var postRotations = [""];
var preMoves = ["U", "U'"];
var postMoves = preMoves;
var selCases = [];
var maxAlgsPerRow = 8;